services:
- docker
env:
  global:
  - DOCKER_COMPOSE_VERSION=1.29.2
  - secure: j8gip4DEl16nMA9/FI+ptyllKNblf3fpOn+w5Ocie9lmrMQqkT3A8tJCMiOPvXVokXJUbviWImygrrfNDWsPqxVFZqNzszggT/7g/k9gQktG6EcvWmKpgxvWU24umxsxJGHNqjQ5HRs4eziu+cVxoGuPYBeK8ZhT7qp47wMdpaZEaFC062yWvFX6htT0gQG/V/M1HFkB3x+dF+chlsEiiCM7cLueNG40/OIMLwYzdRx6AI3WUGLNbAfZdNueKk4/x0gxJp1duiA/6LCKRFHEZpCqn08qcghUGrKhiqCmzsLzttEZDA5oYAqOZjz+/unTy1+xgHUxPkZLNmEDX12pUjCnJnzg5sz6D7kEtGFBfHLlMAF/Q3S7Omlr1pulWEbO2ZKoBCSHIN6+FkXXPIHsDpxAGqMcmqFAqMGdqlxLllZ7KE/OxtXThveDrXLlBl0crHMqoznVUNdzra+YEEBu3FmXnqQQplJWaC2bIWML1VxoXweL3/uL741vNNJGJ59uTEzlchQbFuiEB9ej0RNrkLuYXHpoVDEfW/DlklrfnVv4GOQO64nxKP1LmiO/Dnd0ctFiFawgMmk9KQk7cel4hnf+r9EGSlLCPC0O9gY9PjdyWpTDJZQUkniPctBH1cKTW3jiCmbQIlViTAcsH+fQT4SwLYyti+KUhz7cV/Ye9/M=
  - secure: oaY+Rb6iZr5DwakgjLzp11FhhSpRdAhYVeT+wuR2XxcCvIV73uT3IwNYY/ltzjWOgZjDR6WyKsvckubbQnXR7n/raUcQEEWmwYKozghmhHkpVG8OksArSjtVhKc+c9dW4zzxiRWqBD87OQwEgyegbFbOZxm0o/l48CMEkIzTk9MIt6h+XVAmX5mODgACLlFukc64gtNeDPhceX+8YeIoSOjE9VhVuigNcXL8xCMjVgwsaTtVHR+P+QOV0INOtxCy+jWSj8qDocEKqy8kXLHgEwOqwc6tEYxYHk7QlE8H6FrKtJUA36LiLl21d5FgKebrMau1OMuMrTzMaP/CHD22xTI+qC7m1Y49wtTymdxL6tjl5i1bLkt78AhqccciaRx45Cyxw8pJm3t/ugdgSatmoO8XMd+B7VIKf9sscQUi6khUrqyEdWfrW34YE20xTGbNE8OqX1JJzfQLNV1fBN5SfkReb4X5sNvh/NzXooCzlkokIszFEjlz8xv3AQovVIpbCQ/k6/BIuqdB0wDvPVvnSwDACO7Lp93DmdHPhVCBlcQqk8Tdlo7PPRT9fw4Xrzk6q/uFZFboeS0ct1Zz1LcbWsazzTeg7dQuhU75P+4Ah9c10S7OObzFK6oMMO2CX2thJ4bWmB+PQ5dd6BqP8mXZYLAOSAVgzI8cna2NNwT1o48=
before_install:
- sudo rm /usr/local/bin/docker-compose
- curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname
  -s`-`uname -m` > docker-compose
- chmod +x docker-compose
- sudo mv docker-compose /usr/local/bin
- docker --version
- docker-compose version
- echo "Login into Docker Hub"
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- export GIT_SHA=`git rev-parse --short HEAD`
- echo "Building commit $GIT_SHA"
jobs:
  include:
  - stage: tests
    name: Unit Tests
    script:
    - cd Chapter04
    - docker-compose build db
    - docker-compose build test-postgresql
    - docker-compose run test-postgresql
  - stage: tests
    name: Static Analysis
    script:
    - cd Chapter04
    - docker-compose build static-analysis
    - docker-compose run static-analysis
  - stage: push
    script:
    - cd Chapter04
    - docker-compose build server
    - docker tag thoughts_server:latest renanvicente/thoughts-backend:$GIT_SHA
    - docker push renanvicente/thoughts-backend:$GIT_SHA
    - docker tag thoughts_server:latest renanvicente/thoughts-backend:$TRAVIS_BRANCH
    deploy:
    - provider: script
      script: docker push renanvicente/thoughts-backend:$TRAVIS_BRANCH
      on:
        branch: master
    - provider: script
      script: docker push renanvicente/thoughts-backend:$TRAVIS_TAG
      on:
        tags: true
